In [1]:
import pandas as pd
import numpy as np

In [2]:
# heterogenous data type
# store the value and datatype for each value
my_list = [1, 'Colorado', 4.8]
my_list

[1, 'Colorado', 4.8]

In [3]:
my_list[0]

1

In [4]:
my_list[2]

4.8

In [5]:
my_list[-1]

4.8

In [6]:
# homogeneous datatypes
# datatype stored only the 1st time
# faster when using in functions
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

In [7]:
my_array = np.array((2,3,4))
my_array

array([2, 3, 4])

In [8]:
my_array[0]

2

In [9]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [10]:
my_array/3

array([0.33333333, 0.66666667, 1.        ])

In [11]:
my_list/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [18]:
# appended in place
my_list.append('new thing')
my_list

[1,
 2,
 3,
 'new thing',
 'new thing',
 'new thing',
 'new thing',
 'new thing',
 'new thing',
 'new thing']

In [19]:
# returns a new array; not in-place
# 
my_array = np.append(my_array, 5)
my_array

array([1, 2, 3, 5])

In [20]:
# dictionaries
# k-v pairs: k - indexes used to find the values
# keys should be unique

my_dict = {'key1': 'first value', 'key2': 'second value'}
my_dict

{'key1': 'first value', 'key2': 'second value'}

In [21]:
my_dict['key1']

'first value'

In [22]:
my_dict['new key'] = 'newest value'
my_dict['new key']

'newest value'

In [23]:
my_dict['int'] = 5
my_dict['int']

5

In [24]:
# dictionaries imp in creating dataframes and changing dataframes
df = pd.DataFrame({'col1':range(0,3), 'col2':range(3,6)})
df

col1  col2
0     0     3
1     1     4
2     2     5

In [25]:
df.rename(columns = {'col1':'apples', 'col2':'oranges'})
df

col1  col2
0     0     3
1     1     4
2     2     5